language: cpp

os:
- linux
- osx

dist: trusty

python: '2.7'

before_script:
  - ./ensure_dependencies.py
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - nvm install 8.9.4
  - npm install

script:
  - npm test

notifications:
  email: false
