language: cpp

os:
- linux
- osx

dist: trusty

python: '2.7'

addons:
  apt:
    packages:
    - ninja-build

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install ninja; fi
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - nvm install 8.9.4
  - mkdir -p third_party
  - bash .travis/prepare-emscripten.sh

before_script:
  - ./ensure_dependencies.py

script:
  - meson --version
  - npm install
  - npm test

notifications:
  email: false
