language: cpp

os:
- linux
- osx

dist: trusty

python: '2.7'

addons:
  apt:
    packages:
    - ninja-build
    - python3-pip

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install ninja; fi
  - nvm install 8.9.4
  - pip3 install -q --user meson
  - mkdir -p third_party
  - bash .travis/prepare-emscripten.sh

before_script:
  - ./ensure_dependencies.py
  - npm install

script:
  - meson --buildtype debug build/debug 
  - ninja -C build/debug
  - npm test

notifications:
  email: false
