language: cpp

os:
- linux
- osx

dist: trusty

python: '2.7'

addons:
  apt:
    packages:
    - python3-pip

env:
  global:
    - PATH=${PATH}:${TRAVIS_BUILD_DIR}/third_party/ninja
  matrix:
    - BUILDTYPE=release
    - BUILDTYPE=debug

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - bash .travis/travis-install.sh
  - export PATH=${PATH}:$(python3 -c "import sysconfig;print(sysconfig.get_paths('posix_user')['scripts'])")

before_script:
  - ./ensure_dependencies.py
  - npm install

script:
  - meson --buildtype ${BUILDTYPE} build
  - ninja -C build
  - npm test

notifications:
  email: false
