language: cpp

os:
- linux
- osx

dist: trusty

python: '2.7'

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - python3-pip
    - libstdc++6

env:
  global:
    - PATH=${PATH}:${TRAVIS_BUILD_DIR}/third_party/ninja
  matrix:
    - BUILDTYPE=release
    - BUILDTYPE=debug

install:
  - nvm install 8.9.4
  - mkdir -p third_party
  - bash .travis/prepare-emscripten.sh
  - bash .travis/prepare-ninja.sh
  - pip3 install -q --user meson

before_script:
  - ./ensure_dependencies.py
  - npm install

script:
  - meson --buildtype ${BUILDTYPE} build/${BUILDTYPE}
  - ninja -C build/${BUILDTYPE}
  - npm test

notifications:
  email: false
